version: '3.8'

services:
  meetingbot:
    build: .
    container_name: meetingbot
    env_file:
      - .env
    volumes:
      # Пробрасываем sessions/ наружу для сохранения скриншотов
      - ./sessions:/app/sessions
    # Добавляем shm-size для Chrome в headless режиме
    shm_size: 2gb
    # Убираем автоперезапуск - бот должен завершиться после AUTO_DISCONNECT_SECONDS
    # restart: unless-stopped
    # Увеличиваем таймаут для graceful shutdown (по умолчанию 10 сек)
    stop_grace_period: 30s
